const products=[
{id:1,name:'Carrara White Marble',sku:'TV-MAR-6012',room:'Living Room',type:'Floor',color:'White',finish:'Glossy',size:'600×1200',price:110,stock:86,coverage:15.5,img:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80'},
{id:2,name:'Urban Grey Stone',sku:'TV-GRY-6060',room:'Bathroom',type:'Floor',color:'Grey',finish:'Anti-Skid',size:'600×600',price:68,stock:42,coverage:15.5,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80'},
{id:3,name:'Oakwood Natural',sku:'TV-WOD-2012',room:'Bedroom',type:'Floor',color:'Brown',finish:'Matt',size:'200×1200',price:92,stock:24,coverage:14.0,img:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80'},
{id:4,name:'Pearl Beige',sku:'TV-BEG-6060',room:'Kitchen',type:'Wall',color:'Beige',finish:'Glossy',size:'600×600',price:59,stock:180,coverage:15.5,img:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80'},
{id:5,name:'Charcoal Slate',sku:'TV-BLK-6060',room:'Outdoor',type:'Floor',color:'Black',finish:'Anti-Skid',size:'600×600',price:75,stock:8,coverage:15.5,img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80'},
{id:6,name:'Ivory Concrete',sku:'TV-IVR-6012',room:'Living Room',type:'Floor',color:'White',finish:'Matt',size:'600×1200',price:82,stock:0,coverage:15.5,img:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80'},
{id:7,name:'Sage Green Decor',sku:'TV-GRN-3060',room:'Bathroom',type:'Wall',color:'Green',finish:'Matt',size:'300×600',price:72,stock:55,coverage:12.0,img:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80'},
{id:8,name:'Royal Black Marble',sku:'TV-BLK-6012',room:'Living Room',type:'Floor',color:'Black',finish:'High Gloss',size:'600×1200',price:135,stock:31,coverage:15.5,img:'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=900&q=80'}];
let state={view:'home',query:'',room:'',color:'',finish:'',quote:[],wish:[],area:120};
const app=document.getElementById('app');
function nav(){return `<div class="top"><span>Free showroom consultation & area calculation</span><span>📞 +91 98765 43210 &nbsp; | &nbsp; WhatsApp</span></div><nav class="nav"><div class="logo">Tile<span>Vista</span></div><div class="navlinks"><button onclick="go('home')">Home</button><button onclick="go('catalog')">Tiles</button><button onclick="go('calculator')">Calculator</button><button onclick="go('inspiration')">Inspiration</button><button onclick="go('admin')">Admin Demo</button></div><button class="secondary" onclick="openQuote()">Quote (${state.quote.length})</button></nav>`}
function hero(){return `<section class="hero"><div class="hero-inner"><div class="eyebrow">Digital Tile Showroom</div><h1>Find the right tile for every space.</h1><p>Search by room, colour, size, finish or budget. See live stock, calculate quantity and build your quotation in minutes.</p><div class="search"><input value="${state.query}" oninput="state.query=this.value;render()" placeholder="Try: white bathroom tile, grey 600x600, under ₹80…"><button class="primary" onclick="go('catalog')">Search Tiles</button></div></div></section>`}
function spaces(){let s=[['🏠','Living Room'],['🚿','Bathroom'],['🍳','Kitchen'],['🛏️','Bedroom'],['🌳','Outdoor'],['🚗','Parking']];return `<section class="section"><h2>Shop by space</h2><p class="sub">Tell us where the tile will be used and we'll narrow the choices.</p><div class="spacegrid">${s.map(x=>`<button class="space" onclick="state.room='${x[1]}';go('catalog')"><span class="emoji">${x[0]}</span>${x[1]}</button>`).join('')}</div></section>`}
function chips(){return `<section class="section"><h2>Shop by colour</h2><p class="sub">Popular colour families for quick discovery.</p><div class="chips">${['White','Grey','Beige','Brown','Black','Green'].map(c=>`<button class="chip" onclick="state.color='${c}';go('catalog')">${c}</button>`).join('')}</div></section>`}
function card(p){let st=p.stock===0?'out':p.stock<15?'low':'ok',txt=p.stock===0?'Out of stock':p.stock<15?`Only ${p.stock} boxes`:`${p.stock} boxes available`;return `<article class="product"><div class="tileimg" style="background-image:url('${p.img}')"><span class="stock ${st}">${txt}</span><button class="heart" onclick="toggleWish(${p.id})">${state.wish.includes(p.id)?'♥':'♡'}</button></div><div class="pbody"><h3>${p.name}</h3><div class="meta">${p.size} · ${p.finish} · ${p.color}<br>${p.room} · ${p.sku}</div><div class="price">₹${p.price} <small>/ sq.ft.</small></div><div class="actions"><button class="secondary" onclick="details(${p.id})">Details</button><button class="primary" ${p.stock===0?'disabled':''} onclick="addQuote(${p.id})">Add to Quote</button></div></div></article>`}
function catalogue(){let arr=products.filter(p=>{let q=state.query.toLowerCase();return(!q||`${p.name} ${p.color} ${p.room} ${p.size} ${p.finish}`.toLowerCase().includes(q))&&(!state.room||p.room===state.room)&&(!state.color||p.color===state.color)&&(!state.finish||p.finish===state.finish)});return `<section class="section"><h2>Explore tiles</h2><p class="sub">${arr.length} products match your requirements. <button class="secondary" onclick="state.room='';state.color='';state.finish='';state.query='';render()">Clear filters</button></p><div class="layout"><aside class="filters"><h3>Filters</h3><div class="filter-group"><label>Room</label><select onchange="state.room=this.value;render()"><option value="">All rooms</option>${['Living Room','Bathroom','Kitchen','Bedroom','Outdoor'].map(x=>`<option ${state.room===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="filter-group"><label>Colour</label><select onchange="state.color=this.value;render()"><option value="">All colours</option>${['White','Grey','Beige','Brown','Black','Green'].map(x=>`<option ${state.color===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="filter-group"><label>Finish</label><select onchange="state.finish=this.value;render()"><option value="">All finishes</option>${['Glossy','Matt','Anti-Skid','High Gloss'].map(x=>`<option ${state.finish===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="filter-group"><label>Availability</label><label><input type="checkbox" onchange="this.checked?state.query+=' ':state.query=state.query"> Show in-stock first</label></div></aside><div class="products">${arr.map(card).join('')||'<div class="panel"><h3>No tiles found</h3><p>Try a different colour, room or search term.</p></div>'}</div></div></section>`}
function calculator(){return `<section class="section"><h2>Tile quantity & cost calculator</h2><p class="sub">Calculate approximate tile requirement and check whether enough stock is available.</p><div class="calc"><div class="panel"><div class="fields"><div class="field"><label>Length (ft)</label><input id="len" type="number" value="12"></div><div class="field"><label>Width (ft)</label><input id="wid" type="number" value="10"></div><div class="field"><label>Wastage %</label><input id="waste" type="number" value="10"></div><div class="field"><label>Tile</label><select id="tile">${products.map(p=>`<option value="${p.id}">${p.name} — ₹${p.price}/sq.ft.</option>`).join('')}</select></div></div><button class="primary" style="margin-top:18px" onclick="calculate()">Calculate</button></div><div class="panel"><div id="calcresult" class="result"><div>Enter room dimensions and select a tile.</div></div></div></div></section>`}
function inspiration(){return `<section class="section"><h2>Room inspiration</h2><p class="sub">Explore combinations and turn a look into a quotation.</p><div class="products">${[['Modern Living','Carrara White + Charcoal Accent'],['Calm Bathroom','Urban Grey + Pearl White'],['Warm Bedroom','Oakwood Natural + Ivory']].map((x,i)=>`<div class="product"><div class="tileimg" style="background-image:url('${products[i*2].img}')"></div><div class="pbody"><h3>${x[0]}</h3><div class="meta">${x[1]}</div><button class="primary" style="margin-top:12px;width:100%" onclick="go('catalog')">Shop this look</button></div></div>`).join('')}</div></section>`}
function admin(){return `<section class="section"><div style="display:flex;justify-content:space-between;align-items:end"><div><h2>Owner dashboard</h2><p class="sub">Simple controls for showroom staff.</p></div><button class="primary" onclick="go('catalog')">Back to showroom</button></div><div class="dash"><div class="stat"><small>Today's Sales</small><b>₹2.45L</b></div><div class="stat"><small>New Leads</small><b>27</b></div><div class="stat"><small>Low Stock</small><b>14</b></div><div class="stat"><small>Outstanding</small><b>₹8.2L</b></div></div><div class="table"><table><thead><tr><th>SKU</th><th>Product</th><th>Stock</th><th>Price</th><th>Status</th></tr></thead><tbody>${products.map(p=>`<tr><td>${p.sku}</td><td>${p.name}</td><td>${p.stock} boxes</td><td>₹${p.price}/sq.ft.</td><td><span class="badge">${p.stock?'Available':'Out of stock'}</span></td></tr>`).join('')}</tbody></table></div><div class="panel" style="margin-top:18px"><h3>Quick actions</h3><div class="chips"><button class="chip" onclick="alert('Product import flow: upload Excel/CSV → validate → preview → import.')">+ Add / Import Products</button><button class="chip" onclick="openQuote()">Create Invoice / Quote</button><button class="chip" onclick="alert('Low-stock report ready for purchase planning.')">Low-stock Report</button></div></div></section>`}
function home(){return hero()+spaces()+chips()+`<section class="section"><div class="banner"><div><h2>Need help choosing?</h2><p>Tell us your room, colour, area and budget. Our team can recommend available tiles.</p></div><button class="primary" onclick="openAdvisor()">Get Recommendation</button></div></section>`+`<section class="section"><h2>Popular tiles</h2><p class="sub">Live catalogue with stock visibility.</p><div class="products">${products.slice(0,3).map(card).join('')}</div></section>`}
function render(){app.innerHTML=nav()+(state.view==='catalog'?catalogue():state.view==='calculator'?calculator():state.view==='inspiration'?inspiration():state.view==='admin'?admin():home())+`<footer class="footer"><div class="footer-inner"><div><div class="logo" style="color:#fff">Tile<span>Vista</span></div><p style="color:#b8c5d3">Digital showroom, stock and billing platform.</p></div><div><b>Showroom</b><p style="color:#b8c5d3">Mon–Sat · 9:30 AM–8:00 PM<br>+91 98765 43210</p></div></div></footer>`}
function go(v){state.view=v;render();scrollTo(0,0)}
function addQuote(id){if(!state.quote.includes(id))state.quote.push(id);openQuote()}
function toggleWish(id){state.wish.includes(id)?state.wish=state.wish.filter(x=>x!==id):state.wish.push(id);render()}
function details(id){let p=products.find(x=>x.id===id);document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modalbox"><div class="modalhead"><h2>${p.name}</h2><button class="close" onclick="document.getElementById('modal').remove()">×</button></div><img src="${p.img}" style="width:100%;height:250px;object-fit:cover;border-radius:12px"><p><b>SKU:</b> ${p.sku}<br><b>Size:</b> ${p.size}<br><b>Finish:</b> ${p.finish}<br><b>Usage:</b> ${p.room}<br><b>Coverage:</b> ${p.coverage} sq.ft./box<br><b>Live stock:</b> ${p.stock} boxes</p><h3>₹${p.price}/sq.ft.</h3><button class="primary" onclick="addQuote(${p.id});document.getElementById('modal').remove()">Add to Quote</button></div></div>`)}
function openQuote(){let ps=state.quote.map(id=>products.find(p=>p.id===id));document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="quote"><div class="modalbox"><div class="modalhead"><h2>My quotation</h2><button class="close" onclick="document.getElementById('quote').remove()">×</button></div>${ps.length?ps.map(p=>`<div class="quote-row"><span>${p.name}<br><small>${p.stock} boxes available</small></span><b>₹${p.price}/sq.ft.</b></div>`).join(''):'<p>Your quote is empty. Add products from the catalogue.</p>'}<div style="margin-top:20px;display:flex;gap:10px"><button class="primary" onclick="alert('Demo: enquiry submitted. In production this creates a lead in the admin panel.')">Request Quote</button><button class="secondary" onclick="alert('Demo: WhatsApp message generated.')">WhatsApp</button></div></div></div>`)}
function openAdvisor(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="advisor"><div class="modalbox"><div class="modalhead"><h2>Tile recommendation</h2><button class="close" onclick="document.getElementById('advisor').remove()">×</button></div><div class="fields"><div class="field"><label>Room</label><select id="aroom"><option>Living Room</option><option>Bathroom</option><option>Kitchen</option><option>Bedroom</option><option>Outdoor</option></select></div><div class="field"><label>Colour</label><select id="acolor"><option>White</option><option>Grey</option><option>Beige</option><option>Brown</option><option>Black</option><option>Green</option></select></div><div class="field"><label>Budget / sq.ft.</label><input id="abudget" type="number" value="90"></div><div class="field"><label>Area / sq.ft.</label><input id="aarea" type="number" value="200"></div></div><button class="primary" style="margin-top:18px" onclick="recommend()">Recommend Tiles</button><div id="recs" style="margin-top:18px"></div></div></div>`)}
function recommend(){let room=document.getElementById('aroom').value,color=document.getElementById('acolor').value,budget=+document.getElementById('abudget').value,area=+document.getElementById('aarea').value;let r=products.map(p=>({...p,score:(p.room===room?35:0)+(p.color===color?25:0)+(p.price<=budget?25:0)+(p.stock*p.coverage>=area*1.1?15:0)})).sort((a,b)=>b.score-a.score).slice(0,3);document.getElementById('recs').innerHTML=`<h3>Recommended for ${room}</h3>`+r.map(p=>`<div class="quote-row"><span><b>${p.name}</b><br><small>${p.color} · ${p.finish} · ${p.size} · ${p.stock} boxes available</small></span><b>${p.score}/100</b></div>`).join('')}
function calculate(){let l=+document.getElementById('len').value,w=+document.getElementById('wid').value,wa=+document.getElementById('waste').value,p=products.find(x=>x.id==document.getElementById('tile').value);let area=l*w,required=area*(1+wa/100),boxes=Math.ceil(required/p.coverage),total=required*p.price,available=p.stock>=boxes;document.getElementById('calcresult').innerHTML=`<div>Room area <b>${area.toFixed(1)} sq.ft.</b></div><div style="margin:10px 0">Required with wastage <b>${required.toFixed(1)} sq.ft.</b></div><div>Estimated quantity <b>${boxes} boxes</b></div><div style="margin-top:12px">Estimated tile cost</div><strong>₹${Math.round(total).toLocaleString('en-IN')}</strong><p>${available?'🟢 Enough stock available':'🔴 Not enough stock — choose another tile or contact showroom.'}</p>`}
render();
